# defaultContentLanguageInSubdir must be true for this to work.

# Other languages redirects
# [[redirects]]
# from = '/fr/**'
# to = '/fr/404.html'
# status = 404

# Default language must be last.
[[redirects]]
from = '/**'
to = '/jobrunr-website-rework/404.html'
status = 404
